import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.io.Serializable;
import java.util.Date;

// Serializable interface required by Java
public class User implements Serializable {
    // Required by Java
    private static final long serialVersionUID = 1L;
    @JsonSerialize
    @JsonDeserialize
    private String username;
    @JsonDeserialize
    @JsonSerialize
    private Date registrationDate;

    // Required by Jackson, auto generated by Java if not other ctor defined
    public User(){}

    // Getters and setters required by Jackson
    // Alternative: public fields, or annotated fields
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Date getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    @Override
    public String toString() {
        return "User{" +
                "username='" + username + '\'' +
                ", registrationDate=" + registrationDate +
                '}';
    }
}
